<nav class="navbar">
<div class="logo">
        <img src="./images/logo1.png" alt="Paw Logo">
    <div class="dropdown">
    <select onchange="location = this.value;">
        <option selected disabled>Select a Page...</option>
        <option value="index.php">Home</option>
        <option value="pets.php">Pets</option>
        <option value="gallery.php">Gallery</option>
        <option value="add.php">Add More</option>
    </select>
    </div>
</div>

    <div class="search-container">
        <input type="text" placeholder="Search">
        <button type="submit">
            <i class="fas fa-search"></i>
        </button>
    </div>
</nav>
